APP_PORT: 9191
CONSUMER_AS_WORKER_PORT: 9192
LOG_LEVEL: "info"
LOG_FORMAT: "text"
SENTRY_DSN: "dsn"
SENTRY_ENABLED: false
KAFKA_BROKER_LIST: "pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092"
KAFKA_BULK_PUBLISH_TOPIC: "sample-message-bulk"
KAFKA_INTERNAL_PUBLISH_TOPIC: "app-message-internal"
KAFKA_MAX_CONNECTIONS: 50
KAFKA_TRANSACTIONAL_PUBLISH_TOPIC: "public-txns"
KAFKA_RETRY_IN_MILLISECONDS: 1000
KAFKA_CONSUME_OFFSET: "latest"
KAFKA_CONSUMER_GROUP: "service-consumer-group"
KAFKA_WORKER_COUNT: 1
KAFKA_LINGER_MS: 100
KAFKA_RETRY_BACKOFF_MS: 1000
KAFKA_MESSAGE_TIMEOUT_MS: 45000
KAFKA_PUBLISH_BATCH_SIZE: 10
CONSUMER_NUM_MESSAGES_PROCESSED_PER_SECOND: 100

CONS_KAFKA_BROKER_LIST: "pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092"
CONS_KAFKA_BULK_PUBLISH_TOPIC: "demo-message-bulk"
CONS_KAFKA_INTERNAL_PUBLISH_TOPIC: "message-internal"
CONS_KAFKA_MAX_CONNECTIONS: 50
CONS_KAFKA_TRANSACTIONAL_PUBLISH_TOPIC: "public-message"
CONS_KAFKA_RETRY_IN_MILLISECONDS: 200
CONS_KAFKA_CONSUME_OFFSET: "latest"
CONS_KAFKA_CONSUMER_GROUP: "consumer-service-group"
CONS_KAFKA_WORKER_COUNT: 1
CONS_KAFKA_LINGER_MS: 100
CONS_KAFKA_RETRY_BACKOFF_MS: 1000
CONS_KAFKA_MESSAGE_TIMEOUT_MS: 1000
CONS_KAFKA_PUBLISH_BATCH_SIZE: 10
CONS_KAFKA_MAX_RETRIES: 5