APP_PORT: 9191
LOG_LEVEL: "info"
LOG_FORMAT: "text"
SENTRY_DSN: "dsn"
SENTRY_ENABLED: false
KAFKA_BROKER_LIST: "localhost:9092"
KAFKA_BULK_PUBLISH_TOPIC: "sample-message-bulk"
KAFKA_INTERNAL_PUBLISH_TOPIC: "app-message-internal"
KAFKA_MAX_CONNECTIONS: 50
KAFKA_TRANSACTIONAL_PUBLISH_TOPIC: "public-txns"
KAFKA_RETRY_IN_MILLISECONDS: 1000
KAFKA_CONSUME_OFFSET: "latest"
KAFKA_CONSUMER_GROUP: "service-consumer-group"
KAFKA_WORKER_COUNT: 1
KAFKA_LINGER_MS: 100
KAFKA_RETRY_BACKOFF_MS: 1000
KAFKA_MESSAGE_TIMEOUT_MS: 1000
KAFKA_PUBLISH_BATCH_SIZE: 10